name: Publish Gradle Package

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Or your desired Java version
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Package
        run: ./gradlew clean build -x test

      - name: Publish to GitHub Packages
        run: ./gradlew publish --info
        env:
          gpr.user: sumanpalakolu@gmail.com
          gpr.key: ${{ secrets.G_TOKEN }}
